-- 
CREATE TABLE Users (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Username NVARCHAR(50) UNIQUE NOT NULL,
    Email NVARCHAR(100) UNIQUE NOT NULL,
    Phone NVARCHAR(20) NULL,
    PasswordHash NVARCHAR(255) NOT NULL,
    AvatarUrl NVARCHAR(255) NULL,
    DisplayName NVARCHAR(100),
    IsSearchable BIT DEFAULT 1,
    LastSeen DATETIME NULL,
    IsOnline BIT DEFAULT 0,
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE()
);

CREATE TABLE OtpRequests (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(Id),
    Code NVARCHAR(10) NOT NULL,
    ExpiredAt DATETIME NOT NULL,
    IsUsed BIT DEFAULT 0,
    CreatedAt DATETIME DEFAULT GETDATE()
);

CREATE TABLE Friends (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    RequesterId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(Id),
    AddresseeId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(Id),
    Status NVARCHAR(20) CHECK (Status IN ('pending', 'accepted', 'blocked')) NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE()
);

CREATE TABLE Conversations (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    IsGroup BIT DEFAULT 0,
    Name NVARCHAR(100) NULL,
    AvatarUrl NVARCHAR(255) NULL,
    CreatedBy UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(Id),
    CreatedAt DATETIME DEFAULT GETDATE()
);

CREATE TABLE ConversationMembers (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    ConversationId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Conversations(Id),
    UserId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(Id),
    Role NVARCHAR(20) DEFAULT 'member',
    JoinedAt DATETIME DEFAULT GETDATE()
);

CREATE TABLE Messages (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    ConversationId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Conversations(Id),
    SenderId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(Id),
    MessageType NVARCHAR(20) CHECK (MessageType IN ('text', 'image', 'video', 'audio', 'file')) DEFAULT 'text',
    Content NVARCHAR(MAX),
    SentAt DATETIME DEFAULT GETDATE(),
    IsDeleted BIT DEFAULT 0,
    IsEdited BIT DEFAULT 0
);

CREATE TABLE MessageStatus (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    MessageId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Messages(Id),
    UserId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(Id),
    IsRead BIT DEFAULT 0,
    ReadAt DATETIME NULL
);

CREATE TABLE UserSettings (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(Id),
    MuteAllNotifications BIT DEFAULT 0,
    PinSecurityCode NVARCHAR(10) NULL,
    EnableE2E BIT DEFAULT 0,
    ChatTheme NVARCHAR(50) NULL,
    UpdatedAt DATETIME DEFAULT GETDATE()
);

CREATE TABLE ConversationSettings (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(Id),
    ConversationId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Conversations(Id),
    MuteNotification BIT DEFAULT 0,
    Pinned BIT DEFAULT 0,
    CustomColor NVARCHAR(20) NULL
);

CREATE TABLE Attachments (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    MessageId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Messages(Id),
    FileUrl NVARCHAR(255),
    FileType NVARCHAR(50),
    FileSize BIGINT,
    UploadedAt DATETIME DEFAULT GETDATE(),
    AttType NVARCHAR(20) CHECK (AttType IN ('image', 'video', 'audio', 'file', 'link')) NOT NULL
);

