CREATE TABLE Users (
    Guid UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Username NVARCHAR(50) UNIQUE NOT NULL,
    Email NVARCHAR(100) UNIQUE NOT NULL,
    Phone NVARCHAR(20) NULL,
    PasswordHash NVARCHAR(255) NOT NULL,
    AvatarUrl NVARCHAR(255) NULL,
    DisplayName NVARCHAR(100),
    IsSearchable BIT DEFAULT 1,
    LastSeen DATETIME NULL,
    IsOnline BIT DEFAULT 0,
    CreatedAt DATETIME DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME DEFAULT GETUTCDATE(),
    IsDeleted BIT DEFAULT 0,
    DeletedAt DATETIME NULL
);

CREATE TABLE OtpRequests (
    Guid UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(Guid),
    Code NVARCHAR(10) NOT NULL,
    ExpiredAt DATETIME NOT NULL,
    IsUsed BIT DEFAULT 0,
    CreatedAt DATETIME DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME DEFAULT GETUTCDATE(),
    IsDeleted BIT DEFAULT 0,
    DeletedAt DATETIME NULL
);

CREATE TABLE Friends (
    Guid UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    RequesterId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(Guid),
    AddresseeId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(Guid),
    Status NVARCHAR(20) CHECK (Status IN ('pending', 'accepted', 'blocked')) NOT NULL,
    CreatedAt DATETIME DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME DEFAULT GETUTCDATE(),
    IsDeleted BIT DEFAULT 0,
    DeletedAt DATETIME NULL
);

CREATE TABLE Conversations (
    Guid UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    IsGroup BIT DEFAULT 0,
    Name NVARCHAR(100) NULL,
    AvatarUrl NVARCHAR(255) NULL,
    CreatedBy UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(Guid),
    CreatedAt DATETIME DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME DEFAULT GETUTCDATE(),
    IsDeleted BIT DEFAULT 0,
    DeletedAt DATETIME NULL
);

CREATE TABLE ConversationMembers (
    Guid UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    ConversationId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Conversations(Guid),
    UserId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(Guid),
    Role NVARCHAR(20) DEFAULT 'member',
    JoinedAt DATETIME DEFAULT GETUTCDATE(),
    CreatedAt DATETIME DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME DEFAULT GETUTCDATE(),
    IsDeleted BIT DEFAULT 0,
    DeletedAt DATETIME NULL
);

CREATE TABLE Messages (
    Guid UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    ConversationId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Conversations(Guid),
    SenderId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(Guid),
    MessageType NVARCHAR(20) CHECK (MessageType IN ('text', 'image', 'video', 'audio', 'file')) DEFAULT 'text',
    Content NVARCHAR(MAX),
    SentAt DATETIME DEFAULT GETUTCDATE(),
    IsEdited BIT DEFAULT 0,
    CreatedAt DATETIME DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME DEFAULT GETUTCDATE(),
    IsDeleted BIT DEFAULT 0,
    DeletedAt DATETIME NULL
);

CREATE TABLE MessageStatus (
    Guid UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    MessageId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Messages(Guid),
    UserId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(Guid),
    IsRead BIT DEFAULT 0,
    ReadAt DATETIME NULL,
    CreatedAt DATETIME DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME DEFAULT GETUTCDATE(),
    IsDeleted BIT DEFAULT 0,
    DeletedAt DATETIME NULL
);

CREATE TABLE UserSettings (
    Guid UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(Guid),
    MuteAllNotifications BIT DEFAULT 0,
    PinSecurityCode NVARCHAR(10) NULL,
    EnableE2E BIT DEFAULT 0,
    ChatTheme NVARCHAR(50) NULL,
    CreatedAt DATETIME DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME DEFAULT GETUTCDATE(),
    IsDeleted BIT DEFAULT 0,
    DeletedAt DATETIME NULL
);

CREATE TABLE ConversationSettings (
    Guid UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(Guid),
    ConversationId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Conversations(Guid),
    MuteNotification BIT DEFAULT 0,
    Pinned BIT DEFAULT 0,
    CustomColor NVARCHAR(20) NULL,
    CreatedAt DATETIME DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME DEFAULT GETUTCDATE(),
    IsDeleted BIT DEFAULT 0,
    DeletedAt DATETIME NULL
);

CREATE TABLE Attachments (
    Guid UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    MessageId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Messages(Guid),
    FileUrl NVARCHAR(2000),
    FileType NVARCHAR(50),
    FileSize BIGINT,
    AttType NVARCHAR(20) CHECK (AttType IN ('image', 'video', 'audio', 'file', 'link')) NOT NULL,
    UploadedAt DATETIME DEFAULT GETUTCDATE(),
    CreatedAt DATETIME DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME DEFAULT GETUTCDATE(),
    IsDeleted BIT DEFAULT 0,
    DeletedAt DATETIME NULL
);
